routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\VisitorController;
use App\Http\Controllers\Payment\XenditController;

// Admin Controller
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\PromoController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\KategoriController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\OrderAdminController;

// User Controller
use App\Http\Controllers\User\DashboardUserController;
use App\Http\Controllers\User\CartController;
use App\Http\Controllers\User\OrderController;
use App\Http\Controllers\User\SettingProfileController;
use App\Http\Controllers\User\ShippingAddressController;

// Kitchen Controller
use App\Http\Controllers\Kitchen\DashboardKitchenController;
use App\Http\Controllers\Kitchen\OrderKitchenController;

use App\Http\Controllers\Kurir\KurirController;

Route::get('/', [VisitorController::class, 'index'])->name('visitor.index');
Route::view('/login', 'visitor-page.login');
Route::get('xendit/va/list', [XenditController::class, 'getVirtualAccount'])->name('xendit.index');
Route::post('xendit/va/callback', [XenditController::class, 'callbackVa']);

//ROUTE untuk ADMIN
// CheckRole 1 untuk Admin
Route::group(['middleware' => ['auth','checkRole:1']], function () {
    Route::prefix('admin')->group(function () {
        Route::resource('role', RoleController::class)->except(['create', 'edit']);
        Route::resource('menu', MenuController::class)->except(['create', 'edit']);
        Route::resource('kategori', KategoriController::class)->except(['create', 'edit']);
        Route::resource('promo', PromoController::class)->except(['create', 'edit']);
        Route::resource('user', UserController::class);
        Route::resource('order-admin', OrderAdminController::class)->only(['index', 'update']);
        Route::get('order-admin/{no_resi}','App\Http\Controllers\Admin\OrderAdminController@getDetail')->name('detail-order');
        Route::resource('about', AboutController::class)->except('destroy');
        Route::get('xendit/va/transaksi', [XenditController::class, 'getTransaksi']);
        Route::get('xendit/invoice', [XenditController::class, 'getInvoice'])->name('xendit.invoice');
        Route::get('xendit/invoice/{external_id}', [XenditController::class, 'detailInvoice'])->name('xendit.detail-invoice');
        Route::prefix('gallery')->group(function () {
            Route::get('/', [GalleryController::class, 'index'])->name('gallery.index');
            Route::post('/store', [GalleryController::class, 'store'])->name('gallery.store');
            Route::get('/delete/{id}', [GalleryController::class, 'destroy'])->name('gallery.delete');
        });
    });
});

// ROUTE untuk KITCHEN
// CheckRole 2 untuk Kitchen
Route::group(['middleware' => ['auth', 'checkRole:2']], function () {
    Route::prefix('kitchen')->group(function () {
        Route::resource('dashboard-kitchen', DashboardKitchenController::class);
        Route::resource('order-kitchen', OrderKitchenController::class);
        Route::get('order/{no_resi}','App\Http\Controllers\Kitchen\OrderKitchenController@getDetail')->name('kitchen-order');
        Route::resource('kurir', KurirController::class);
        Route::match(['put', 'patch'],'status_kurir/{no_resi}', 'App\Http\Controllers\Kurir\KurirController@status_kurir')->name('status_kurir');
    });
});

// ROUTE untuk MEMBER
// CheckRole 3 untuk Member
Auth::routes(['verify' => true]);
Route::group(['middleware' => ['auth', 'verified','checkRole:3']], function (){
    Route::prefix('user')->group(function () {
        Route::resource('dashboard-user', DashboardUserController::class);
        Route::resource('setting-profile', SettingProfileController::class);
        Route::get('cart-list', [CartController::class, 'index'])->name('cart.index');
        Route::post('cart-list', [CartController::class, 'addToCart'])->name('cart.store');
        Route::post('update-cart', [CartController::class, 'updateCart'])->name('cart.update');
        Route::post('remove-cart', [CartController::class, 'removeCart'])->name('cart.remove');
        Route::post('clear-cart', [CartController::class, 'clearAllCart'])->name('cart.clear');
        Route::get('order/{no_resi}','App\Http\Controllers\User\OrderController@getDetail')->name('order-detail');
        Route::get('riwayat/{no_resi}','App\Http\Controllers\User\DashboardUserController@getRiwayat')->name('riwayat-order');
        Route::resource('order', OrderController::class);
        Route::resource('shipping-address', ShippingAddressController::class);
        Route::get('/getKota/{id}', [ShippingAddressController::class, 'getKota'])->name('getKota');
        Route::get('/getKecamatan/{id}', [ShippingAddressController::class, 'getKecamatan'])->name('getKecamatan');
        Route::get('/getKelurahan/{id}', [ShippingAddressController::class, 'getKelurahan'])->name('getKelurahan');
    });
});

resources/views/visitor-layout/float-button.blade.php
<button class="btn btn-secondary-ss" style="position: fixed; bottom:30px; right: 30px; border-radius: 30px" data-bs-toggle="modal" data-bs-target="#modalContactUs">
    <i class="fas fa-headset"></i> Contact Us
</button>

<div class="modal modal-contact fade" id="modalContactUs" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-body text-center">
        <div class="bag mb-2">
            <div class="row">
            <div class="col-12">
                <i class="fab fa-whatsapp"></i> <br>
                <button class="btn btn-secondary-ss">081312341234</button>
            </div>
            <div class="col-12">
                <i class="fab fa-instagram"></i> <br>
                <button class="btn btn-secondary-ss">@spicesignature</button>
            </div>
            <div class="col-12">
                <i class="far fa-envelope"></i> <br>
                <button class="btn btn-secondary-ss">info@spicesignature.com</button>
            </div>
            </div>
        </div>
        <button type="button" class="btn btn-primary-ss" data-bs-dismiss="modal" aria-label="Close">Close</button>
        </div>
    </div>
    </div>
</div>

resources/views/visitor-layout/footer.blade.php
<section id="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="section-title">
                    Spice Signature
                </div>
                <div>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus id nulla laborum illum. Illo exercitationem dolores mollitia minus atque ipsum placeat doloribus unde optio nam rerum ratione praesentium quasi, iusto ducimus eveniet at adipisci, expedita nesciunt? Asperiores eum maiores tempore ad quasi harum, beatae ipsum nihil dignissimos adipisci neque odio.
                </div>
            </div>
            <div class="col-lg-4 text-center">
                <div class="section-title">
                    Navigation
                </div>
                <ul>
                    <li>
                        <a href="#promo">Promo</a>
                    </li>
                    <li>
                        <a href="#about">About Us</a>
                    </li>
                    <li>
                        <a href="#gallery">Gallery</a>
                    </li>
                    <li>
                        <a href="#menu">Menu</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-4">
                <div class="section-title">
                    Contact Us
                </div>
                <div>
                    Gandaria 8 Office Tower, 19th floor Unit B, Jalan Sultan Iskandar Muda No.10 Jakarta 12240 <br> <br>
                    (icon) @instagram <br>
                    (icon) (+62)813 1234-2134 <br>
                    (icon) info@spicesignature.com
                </div>
            </div>
        </div>
    </div>
</section>

<section id="copyright">
    2022 &copy; Spice Signature
</section>

resources/views/visitor-layout/main.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css">

    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.7.3/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.7.3/dist/js/uikit-icons.min.js"></script>

    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Merienda:wght@400;700&display=swap" rel="stylesheet">

    <!-- Style -->
    <link rel="stylesheet" href="{{asset('assets/css/style.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/stisla-custom.css')}}">

    <title>Spices Signature</title>
    <link rel="shortcut icon" href="assets/img/logo/nav-logo.png">

    {!! ReCaptcha::htmlScriptTagJsApi() !!}

</head>
<body style="position: relative">
    @include('visitor-layout.navbar')

    @yield('content')

    @include('visitor-layout.footer')

    @include('visitor-layout.float-button')

    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <script>
        // Open the Modal
        function openModal() {
          document.getElementById("myModal").style.display = "block";
        }

        // Close the Modal
        function closeModal() {
          document.getElementById("myModal").style.display = "none";
        }

        var slideIndex = 1;
        showSlides(slideIndex);

        // Next/previous controls
        function plusSlides(n) {
          showSlides(slideIndex += n);
        }

        // Thumbnail image controls
        function currentSlide(n) {
          showSlides(slideIndex = n);
        }

        function showSlides(n) {
          var i;
          var slides = document.getElementsByClassName("mySlides");
          var dots = document.getElementsByClassName("demo");
          var captionText = document.getElementById("caption");
          if (n > slides.length) {slideIndex = 1}
          if (n < 1) {slideIndex = slides.length}
          for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
          }
          for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
          }
          slides[slideIndex-1].style.display = "block";
          dots[slideIndex-1].className += " active";
          captionText.innerHTML = dots[slideIndex-1].alt;
        }
    </script>
    @yield('js')
</body>
</html>

resources/views/visitor-layout/navbar.blade.php
<section id="navbar">
    <nav class="navbar navbar-light navbar-expand-md bg-faded justify-content-center text-center">
        <div class="container">
            <a href="/" class="navbar-brand d-flex w-50 me-auto">
                <img src="assets/img/logo/nav-logo.png" alt="" style="width: 90px;">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsingNavbar3">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
                <ul class="navbar-nav w-100 justify-content-center">
                    <li class="nav-item active">
                        <a class="nav-link" href="#promo">Promo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#about">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#gallery">Gallery</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#menu">Menu</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav ms-auto w-100 justify-content-end">
                    <li class="nav-item">


                        @if(Auth::user())
                            @if (Auth::user()->role_id == 3)
                                <div class="d-sm-none d-lg-inline-block">
                                    <a href="{{ route('setting-profile.index') }}" class="btn btn-secondary-ss">
                                        Hi, {{ Auth::user()->name }}
                                    </a>
                                </div>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                                @elseif(Auth::user()->role_id == 2)
                                <div class="d-sm-none d-lg-inline-block">
                                    <a href="{{ route('dashboard-kitchen.index') }}" class="btn btn-secondary-ss">
                                        Hi, {{ Auth::user()->name }}
                                    </a>
                                </div>
                                @elseif(Auth::user()->role_id == 1)
                                <div class="d-sm-none d-lg-inline-block">
                                    <a href="{{ route('order-admin.index') }}" class="btn btn-secondary-ss">
                                        Hi, {{ Auth::user()->name }}
                                    </a>
                                </div>
                            @endif
                        @else
                        <a href="/register" class="btn btn-primary-ss" style="background-color: transparent">
                            Register
                        </a>
                        <a href="/login" class="btn btn-secondary-ss">
                            Log In
                        </a>
                        @endif

                    </li>
                </ul>
            </div>
        </div>
    </nav>
</section>