routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\VisitorController;
use App\Http\Controllers\Payment\XenditController;

// Admin Controller
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\PromoController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\KategoriController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\OrderAdminController;

// User Controller
use App\Http\Controllers\User\DashboardUserController;
use App\Http\Controllers\User\CartController;
use App\Http\Controllers\User\OrderController;
use App\Http\Controllers\User\SettingProfileController;
use App\Http\Controllers\User\ShippingAddressController;

// Kitchen Controller
use App\Http\Controllers\Kitchen\DashboardKitchenController;
use App\Http\Controllers\Kitchen\OrderKitchenController;

use App\Http\Controllers\Kurir\KurirController;

Route::get('/', [VisitorController::class, 'index'])->name('visitor.index');
Route::view('/login', 'visitor-page.login');
Route::get('xendit/va/list', [XenditController::class, 'getVirtualAccount'])->name('xendit.index');
Route::post('xendit/va/callback', [XenditController::class, 'callbackVa']);

//ROUTE untuk ADMIN
// CheckRole 1 untuk Admin
Route::group(['middleware' => ['auth','checkRole:1']], function () {
    Route::prefix('admin')->group(function () {
        Route::resource('role', RoleController::class)->except(['create', 'edit']);
        Route::resource('menu', MenuController::class)->except(['create', 'edit']);
        Route::resource('kategori', KategoriController::class)->except(['create', 'edit']);
        Route::resource('promo', PromoController::class)->except(['create', 'edit']);
        Route::resource('user', UserController::class);
        Route::resource('order-admin', OrderAdminController::class)->only(['index', 'update']);
        Route::get('order-admin/{no_resi}','App\Http\Controllers\Admin\OrderAdminController@getDetail')->name('detail-order');
        Route::resource('about', AboutController::class)->except('destroy');
        Route::get('xendit/va/transaksi', [XenditController::class, 'getTransaksi']);
        Route::get('xendit/invoice', [XenditController::class, 'getInvoice'])->name('xendit.invoice');
        Route::get('xendit/invoice/{external_id}', [XenditController::class, 'detailInvoice'])->name('xendit.detail-invoice');
        Route::prefix('gallery')->group(function () {
            Route::get('/', [GalleryController::class, 'index'])->name('gallery.index');
            Route::post('/store', [GalleryController::class, 'store'])->name('gallery.store');
            Route::get('/delete/{id}', [GalleryController::class, 'destroy'])->name('gallery.delete');
        });
    });
});

// ROUTE untuk KITCHEN
// CheckRole 2 untuk Kitchen
Route::group(['middleware' => ['auth', 'checkRole:2']], function () {
    Route::prefix('kitchen')->group(function () {
        Route::resource('dashboard-kitchen', DashboardKitchenController::class);
        Route::resource('order-kitchen', OrderKitchenController::class);
        Route::get('order/{no_resi}','App\Http\Controllers\Kitchen\OrderKitchenController@getDetail')->name('kitchen-order');
        Route::resource('kurir', KurirController::class);
        Route::match(['put', 'patch'],'status_kurir/{no_resi}', 'App\Http\Controllers\Kurir\KurirController@status_kurir')->name('status_kurir');
    });
});

// ROUTE untuk MEMBER
// CheckRole 3 untuk Member
Auth::routes(['verify' => true]);
Route::group(['middleware' => ['auth', 'verified','checkRole:3']], function (){
    Route::prefix('user')->group(function () {
        Route::resource('dashboard-user', DashboardUserController::class);
        Route::resource('setting-profile', SettingProfileController::class);
        Route::get('cart-list', [CartController::class, 'index'])->name('cart.index');
        Route::post('cart-list', [CartController::class, 'addToCart'])->name('cart.store');
        Route::post('update-cart', [CartController::class, 'updateCart'])->name('cart.update');
        Route::post('remove-cart', [CartController::class, 'removeCart'])->name('cart.remove');
        Route::post('clear-cart', [CartController::class, 'clearAllCart'])->name('cart.clear');
        Route::get('order/{no_resi}','App\Http\Controllers\User\OrderController@getDetail')->name('order-detail');
        Route::get('riwayat/{no_resi}','App\Http\Controllers\User\DashboardUserController@getRiwayat')->name('riwayat-order');
        Route::resource('order', OrderController::class);
        Route::resource('shipping-address', ShippingAddressController::class);
        Route::get('/getKota/{id}', [ShippingAddressController::class, 'getKota'])->name('getKota');
        Route::get('/getKecamatan/{id}', [ShippingAddressController::class, 'getKecamatan'])->name('getKecamatan');
        Route::get('/getKelurahan/{id}', [ShippingAddressController::class, 'getKelurahan'])->name('getKelurahan');
    });
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;
    protected $table = 'role';

    protected $fillable = [
        'name'
    ];

    public function user()
    {
        return $this->hasOne('App\Models\User');
    }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class RoleController extends Controller
{
    public function index()
    {
        $data = Role::all();

        return view('admin-page.role.index', compact('data'));
    }

    public function store(Request $request)
    {
        $data = $request->all();

        // dd($data);

        $validated = $request->validate([
            'name' => 'required|unique:role|max:20',
        ]);

        $save = Role::create([
            'name' => $data['name']
        ]);


        return redirect()->route('role.index');
    }

    public function update(Request $request, $id)
    {
        $cari = Role::firstWhere('id', $id);

        $cari->name = $request->name;
        $cari->save();

        return redirect()->route('role.index');
    }

    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        $role->delete();

        return redirect()->route('role.index');
    }
}

resources/views/admin-page/role/crud.blade.php
{{-- Modal Tambah --}}
<form action="{{ route('role.store') }}" method="post" enctype="multipart/form-data">
    @csrf
    <div class="modal fade" id="tambah" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Tambah Data</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Role</label>
                        <input type="text" class="form-control" placeholder="Role User" name="name" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success">Save</button>
                </div>
            </div>
        </div>
    </div>
</form>
{{-- End of Modal Tambah --}}


{{-- Modal Edit --}}
@foreach ($data as $i)
    <div class="modal fade" id="roleEdit{{ $i->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <form action="{{ url('admin/role', $i->id) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PATCH')
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="myModalLabel">Edit Role</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="">Role</label>
                            <input type="text" name="name" class="form-control" value="{{ $i->name }}">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-success">Save</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endforeach
{{-- End of Modal Edit --}}

{{-- Modal Hapus --}}
@foreach ($data as $i)
    <div class="modal fade" id="roleHapus{{ $i->id }}" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <form action="{{ url('admin/role',$i->id) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('DELETE')
            <div class="modal-dialog modal-dialog-centered modal-sm">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="mySmallModalLabel">Hapus Data</h4>
                    </div>
                    <div class="modal-body text-center">
                        Apa anda yakin ingin menghapus data <br>
                         <b>{{$i->name}}</b> ?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Ya</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endforeach
{{-- End of Modal Hapus --}}

resources/views/admin-page/role/index.blade.php
@extends('admin-layout.main')

@section('content')
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>List Role User</h1>
        </div>
        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                    <div class="card-header">
                        <button type="button" class="btn btn-primary m-b-sm" data-toggle="modal" data-target="#tambah"><i class="fa fa-plus"></i> Tambah Data</button>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped" id="tableMenu">
                                <thead>
                                <tr class="text-center">
                                    <th>#</th>
                                    <th>Role</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                    @foreach ($data as $key => $i)
                                    <tr class="text-center">
                                        <td>
                                            {{ $key+1 }}
                                        </td>
                                        <td class="align-middle">
                                            {{ $i->name }}
                                        </td>
                                        <td class="align-middle">
                                            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#roleEdit{{$i->id}}" title="Edit"><i class="fa fa-pencil"></i> Edit</button>
                                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#roleHapus{{$i->id}}" title="Hapus"><i class="fa fa-trash"></i> Hapus</button>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

@include('admin-page.role.crud')

@endsection

@section('js')
    <script type="text/javascript">
        $("#tableMenu").dataTable({
            "columnDefs": [
                { "sortable": false, "targets": [1,5] }
            ]
        });
    </script>

    <script>

        function readURL(input, photo) {
        if (input.files && input.files[0]) {

            var reader = new FileReader();

            reader.onload = function(e) {
            $('.image-upload-wrap').hide();
            photo.attr('src', e.target.result);
            photo.attr('href', e.target.result);
            $('.file-upload-content').show();
            $('.image-title').html(input.files[0].name);
            // $('.file-upload-image').attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);

            } else {
                removeUpload();
            }
        }

        function removeUpload() {
            $('.file-upload-input').replaceWith($('.file-upload-input').clone());
            $('.file-upload-content').hide();
            $('.image-upload-wrap').show();
        }
        $('.image-upload-wrap').bind('dragover', function () {
            $('.image-upload-wrap').addClass('image-dropping');
        });
        $('.image-upload-wrap').bind('dragleave', function () {
            $('.image-upload-wrap').removeClass('image-dropping');
        });

    </script>

    @endsection