routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\VisitorController;
use App\Http\Controllers\Payment\XenditController;

// Admin Controller
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\PromoController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\KategoriController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\OrderAdminController;

// User Controller
use App\Http\Controllers\User\DashboardUserController;
use App\Http\Controllers\User\CartController;
use App\Http\Controllers\User\OrderController;
use App\Http\Controllers\User\SettingProfileController;
use App\Http\Controllers\User\ShippingAddressController;

// Kitchen Controller
use App\Http\Controllers\Kitchen\DashboardKitchenController;
use App\Http\Controllers\Kitchen\OrderKitchenController;

use App\Http\Controllers\Kurir\KurirController;

Route::get('/', [VisitorController::class, 'index'])->name('visitor.index');
Route::view('/login', 'visitor-page.login');
Route::get('xendit/va/list', [XenditController::class, 'getVirtualAccount'])->name('xendit.index');
Route::post('xendit/va/callback', [XenditController::class, 'callbackVa']);

//ROUTE untuk ADMIN
// CheckRole 1 untuk Admin
Route::group(['middleware' => ['auth','checkRole:1']], function () {
    Route::prefix('admin')->group(function () {
        Route::resource('role', RoleController::class)->except(['create', 'edit']);
        Route::resource('menu', MenuController::class)->except(['create', 'edit']);
        Route::resource('kategori', KategoriController::class)->except(['create', 'edit']);
        Route::resource('promo', PromoController::class)->except(['create', 'edit']);
        Route::resource('user', UserController::class);
        Route::resource('order-admin', OrderAdminController::class)->only(['index', 'update']);
        Route::get('order-admin/{no_resi}','App\Http\Controllers\Admin\OrderAdminController@getDetail')->name('detail-order');
        Route::resource('about', AboutController::class)->except('destroy');
        Route::get('xendit/va/transaksi', [XenditController::class, 'getTransaksi']);
        Route::get('xendit/invoice', [XenditController::class, 'getInvoice'])->name('xendit.invoice');
        Route::get('xendit/invoice/{external_id}', [XenditController::class, 'detailInvoice'])->name('xendit.detail-invoice');
        Route::prefix('gallery')->group(function () {
            Route::get('/', [GalleryController::class, 'index'])->name('gallery.index');
            Route::post('/store', [GalleryController::class, 'store'])->name('gallery.store');
            Route::get('/delete/{id}', [GalleryController::class, 'destroy'])->name('gallery.delete');
        });
    });
});

// ROUTE untuk KITCHEN
// CheckRole 2 untuk Kitchen
Route::group(['middleware' => ['auth', 'checkRole:2']], function () {
    Route::prefix('kitchen')->group(function () {
        Route::resource('dashboard-kitchen', DashboardKitchenController::class);
        Route::resource('order-kitchen', OrderKitchenController::class);
        Route::get('order/{no_resi}','App\Http\Controllers\Kitchen\OrderKitchenController@getDetail')->name('kitchen-order');
        Route::resource('kurir', KurirController::class);
        Route::match(['put', 'patch'],'status_kurir/{no_resi}', 'App\Http\Controllers\Kurir\KurirController@status_kurir')->name('status_kurir');
    });
});

// ROUTE untuk MEMBER
// CheckRole 3 untuk Member
Auth::routes(['verify' => true]);
Route::group(['middleware' => ['auth', 'verified','checkRole:3']], function (){
    Route::prefix('user')->group(function () {
        Route::resource('dashboard-user', DashboardUserController::class);
        Route::resource('setting-profile', SettingProfileController::class);
        Route::get('cart-list', [CartController::class, 'index'])->name('cart.index');
        Route::post('cart-list', [CartController::class, 'addToCart'])->name('cart.store');
        Route::post('update-cart', [CartController::class, 'updateCart'])->name('cart.update');
        Route::post('remove-cart', [CartController::class, 'removeCart'])->name('cart.remove');
        Route::post('clear-cart', [CartController::class, 'clearAllCart'])->name('cart.clear');
        Route::get('order/{no_resi}','App\Http\Controllers\User\OrderController@getDetail')->name('order-detail');
        Route::get('riwayat/{no_resi}','App\Http\Controllers\User\DashboardUserController@getRiwayat')->name('riwayat-order');
        Route::resource('order', OrderController::class);
        Route::resource('shipping-address', ShippingAddressController::class);
        Route::get('/getKota/{id}', [ShippingAddressController::class, 'getKota'])->name('getKota');
        Route::get('/getKecamatan/{id}', [ShippingAddressController::class, 'getKecamatan'])->name('getKecamatan');
        Route::get('/getKelurahan/{id}', [ShippingAddressController::class, 'getKelurahan'])->name('getKelurahan');
    });
});

app/Models/About.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class About extends Model
{
    protected $table = 'about';

    protected $fillable = [
        'img_1', 'img_2', 'img_3', 'judul', 'deskripsi',
    ];
}

app/Http/Controllers/Admin/AboutController.php
<?php

namespace App\Http\Controllers\Admin;

use File;
use Alert;
use App\Models\About;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AboutController extends Controller
{
    public function index()
    {
        $about = About::all();
        $data = About::all();
        $data_isExist = About::all()->count() > 0;

        return view('admin-page.about.index', compact('about', 'data_isExist', 'data'));
    }

    public function create()
    {
        return view('admin-page.about.crud');
    }

    public function store(Request $request)
    {
        $data =  $request->all();

        if ($request['id'] == 'null') {
            $query = new About;

        } else {
            $query = About::where('id', $request['id'])->first();
        }

        //IMAGE 1
        $file1 = $request->file('img_1');
        $name1 = $file1->getClientOriginalName();
        $ext1 = $file1->getClientOriginalExtension();
        $img1 = $name1;
        $path1 = $file1->move('assets/admin/about',$img1);

        //IMAGE 2
        $file2 = $request->file('img_2');
        $name2 = $file2->getClientOriginalName();
        $ext2 = $file2->getClientOriginalExtension();
        $img2 = $name2;
        $path2 = $file2->move('assets/admin/about',$img2);

        //IMAGE 3
        $file3 = $request->file('img_3');
        $name3 = $file3->getClientOriginalName();
        $ext3 = $file3->getClientOriginalExtension();
        $img3 = $name3;
        $path3 = $file3->move('assets/admin/about',$img3);

        $query = new About();
        $query->img_1 = $img1;
        $query->img_2 = $img2;
        $query->img_3 = $img3;
        $query->judul = $request['judul'];
        $query->deskripsi = $request['deskripsi'];
        $query->save();

        return redirect()->route('about.index')->with([
            alert()->success('Sukses', 'Data berhasil ditambahkan')
        ]);
    }
    public function update(Request $request, $id)
    {
        $cari = About::firstWhere('id', $id);
        if($request->img_1 != '' || $request->img_1 != null || $request->img_2 != '' || $request->img_2 != null || $request->img_3 != '' || $request->img_3 != null)
        {
            if(File::exists($this->path .'/'. $cari->img))
            {
                File::delete($this->path.'/'.$cari->img);
                File::delete($this->path.'/500/'.$cari->img);
            }

            //JIKA FOLDERNYA BELUM ADA
            if (!File::isDirectory($this->path)) {
                //MAKA FOLDER TERSEBUT AKAN DIBUAT
                File::makeDirectory($this->path);
            }

            //IMAGE 1
            $file1 = $request->file('img_1');
            $name1 = $file1->getClientOriginalName();
            $ext1 = $file1->getClientOriginalExtension();
            $img1 = $name1;
            $path1 = $file1->move('assets/admin/about',$img1);

            //IMAGE 2
            $file2 = $request->file('img_2');
            $name2 = $file2->getClientOriginalName();
            $ext2 = $file2->getClientOriginalExtension();
            $img2 = $name2;
            $path2 = $file2->move('assets/admin/about',$img2);

            //IMAGE 3
            $file3 = $request->file('img_3');
            $name3 = $file3->getClientOriginalName();
            $ext3 = $file3->getClientOriginalExtension();
            $img3 = $name3;
            $path3 = $file3->move('assets/admin/about',$img3);

            // $query = new About();
            $cari->img_1 = $img1;
            $cari->img_2 = $img2;
            $cari->img_3 = $img3;
            $cari->judul = $request['judul'];
            $cari->deskripsi = $request['deskripsi'];
            $cari->save();

            return redirect()->route('about.index');
        } else {
            $cari->judul = $request['judul'];
            $cari->deskripsi = $request['deskripsi'];
            $cari->save();

            return redirect()->route('about.index')->with([
                alert()->success('Sukses', 'Data berhasil diubah')
            ]);
        }
    }
}

resources/views/admin-page/about/crud.blade.php
@extends('admin-layout.main')

@section('content')

<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>About Us</h1>
        </div>
        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <form action="{{ route('about.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <div class="row">
                                    <input type="hidden" class="form-control" name="id">
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="judul">Judul</label>
                                            <input type="text" class="form-control" name="judul">
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="deskripsi">Deskripsi</label>
                                            <textarea name="deskripsi" id="deskripsi"class="form-control"></textarea>
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <label>Image 1</label>
                                        <div class="file-upload">
                                            <img src="" width="80%" id="photo" class="foto_promo1">
                                            <input class="form-control photo" id="foto" accept="image/*" onchange="readURL(this,$(&quot;.foto_promo1&quot;))" name="img_1" type="file">
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <label for="img_2">Image 2</label>
                                        <div class="file-upload">
                                            <img src="" width="80%" id="photo" class="foto_promo2">
                                            <input class="form-control photo" id="foto" accept="image/*" onchange="readURL(this,$(&quot;.foto_promo2&quot;))" name="img_2" type="file">
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <label for="img_3">Image 3</label>
                                        <div class="file-upload">
                                            <img src="" width="80%" id="photo" class="foto_promo3">
                                            <input class="form-control photo" id="foto" accept="image/*" onchange="readURL(this,$(&quot;.foto_promo3&quot;))" name="img_3" type="file">
                                        </div>
                                    </div>
                                    <div class="col-12 mt-3">
                                        <input type="submit" class="btn btn-primary" value="Submit">
                                    </div>
                                </div>
                            </div>
                         </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

@endsection

@section('js')
<script>

    function readURL(input, photo) {
    if (input.files && input.files[0]) {

        var reader = new FileReader();

        reader.onload = function(e) {
        $('.image-upload-wrap').hide();
        photo.attr('src', e.target.result);
        photo.attr('href', e.target.result);
        $('.file-upload-content').show();
        $('.image-title').html(input.files[0].name);
        // $('.file-upload-image').attr('src', e.target.result);
        };

        reader.readAsDataURL(input.files[0]);

        } else {
            removeUpload();
        }
    }

    function removeUpload() {
        $('.file-upload-input').replaceWith($('.file-upload-input').clone());
        $('.file-upload-content').hide();
        $('.image-upload-wrap').show();
    }
    $('.image-upload-wrap').bind('dragover', function () {
        $('.image-upload-wrap').addClass('image-dropping');
    });
    $('.image-upload-wrap').bind('dragleave', function () {
        $('.image-upload-wrap').removeClass('image-dropping');
    });

</script>
@endsection

resources/views/admin-page/about/index.blade.php
@extends('admin-layout.main')

@section('content')
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>About Us</h1>
        </div>
        <div class="section-body">
            <div class="card">
                <div class="card-header">
                    @if ($data_isExist)
                    <a href="#"></a>
                    @else
                    <a class="btn btn-primary" href="{{route('about.create')}}">Tambah Data</a>
                    @endif
                </div>
                <div class="card-body">
                    <table class="table table-striped" id="tableMenu">
                        <thead>
                            <tr>
                                <th>Judul</th>
                                <th>Deskripsi</th>
                                <th>Image 1</th>
                                <th>Image 2</th>
                                <th>Image 3</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($about as $about)
                            <tr>
                                <td>{{ $about->judul }}</td>
                                <td>{{ Str::limit($about->deskripsi, 50) }}</td>
                                <td>
                                    <img src="{{asset('assets/admin/about/'.$about->img_1)}}" alt="" style="width: 150px">
                                </td>
                                <td>
                                    <img src="{{asset('assets/admin/about/'.$about->img_2)}}" alt="" style="width: 150px">
                                </td>
                                <td>
                                    <img src="{{asset('assets/admin/about/'.$about->img_3)}}" alt="" style="width: 150px">
                                </td>
                                <td>
                                    <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#edit{{$about->id}}" title="Edit"><i class="fa fa-pencil"></i> Edit</button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
</div>

@foreach ($data as $i)
<div class="modal fade" id="edit{{ $i->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <form action="{{ url('admin/about', $i->id) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method('PATCH')
        <div class="modal-dialog modal-xl modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Edit Menu</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="">Judul</label>
                        <input type="text" name="judul" class="form-control" value="{{ $i->judul }}">
                    </div>
                    <div class="form-group">
                        <label for="deskripsi">Deskripsi</label>
                        <textarea name="deskripsi" id="deskripsi"class="form-control">{{ $i->deskripsi }}</textarea>
                    </div>
                    <div class="form-group">
                        <label>Image 1</label>
                        <div class="file-upload">
                            <img src="{{ asset('assets/admin/about/'.$i->img_1) }}" width="30%" id="photo" class="foto_promo1">
                            <input class="form-control photo" id="foto" accept="image/*" onchange="readURL(this,$(&quot;.foto_promo1&quot;))" name="img_1" type="file">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Image 2</label>
                        <div class="file-upload">
                            <img src="{{ asset('assets/admin/about/'.$i->img_2) }}" width="30%" id="photo" class="foto_promo2">
                            <input class="form-control photo" id="foto" accept="image/*" onchange="readURL(this,$(&quot;.foto_promo2&quot;))" name="img_2" type="file">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Image 3</label>
                        <div class="file-upload">
                            <img src="{{ asset('assets/admin/about/'.$i->img_3) }}" width="30%" id="photo" class="foto_promo3">
                            <input class="form-control photo" id="foto" accept="image/*" onchange="readURL(this,$(&quot;.foto_promo3&quot;))" name="img_3" type="file">
                        </div>
                    </div>

                    {{-- <div class="form-group">
                        <label>Thumbnail</label>
                        <div class="file-upload">
                            <img src="{{asset('assets/admin/menu/'.$i->img)}}" width="40%" id="photo" class="foto_promo">
                            <input class="form-control photo" id="foto" accept="image/*" onchange="readURL(this,$(&quot;.foto_promo&quot;))" name="img" type="file">
                            <small id="emailHelp" class="form-text text-muted">Requirement foto 500x500 px</small>

                        </div>
                    </div> --}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success">Save</button>
                </div>
            </div>
        </div>
    </form>
</div>

@endforeach

@endsection

@section('js')
<script>

    function readURL(input, photo) {
    if (input.files && input.files[0]) {

        var reader = new FileReader();

        reader.onload = function(e) {
        $('.image-upload-wrap').hide();
        photo.attr('src', e.target.result);
        photo.attr('href', e.target.result);
        $('.file-upload-content').show();
        $('.image-title').html(input.files[0].name);
        // $('.file-upload-image').attr('src', e.target.result);
        };

        reader.readAsDataURL(input.files[0]);

        } else {
            removeUpload();
        }
    }

    function removeUpload() {
        $('.file-upload-input').replaceWith($('.file-upload-input').clone());
        $('.file-upload-content').hide();
        $('.image-upload-wrap').show();
    }
    $('.image-upload-wrap').bind('dragover', function () {
        $('.image-upload-wrap').addClass('image-dropping');
    });
    $('.image-upload-wrap').bind('dragleave', function () {
        $('.image-upload-wrap').removeClass('image-dropping');
    });

</script>
@endsection