routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\VisitorController;
use App\Http\Controllers\Payment\XenditController;

// Admin Controller
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\PromoController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\KategoriController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\OrderAdminController;

// User Controller
use App\Http\Controllers\User\DashboardUserController;
use App\Http\Controllers\User\CartController;
use App\Http\Controllers\User\OrderController;
use App\Http\Controllers\User\SettingProfileController;
use App\Http\Controllers\User\ShippingAddressController;

// Kitchen Controller
use App\Http\Controllers\Kitchen\DashboardKitchenController;
use App\Http\Controllers\Kitchen\OrderKitchenController;

use App\Http\Controllers\Kurir\KurirController;

Route::get('/', [VisitorController::class, 'index'])->name('visitor.index');
Route::view('/login', 'visitor-page.login');
Route::get('xendit/va/list', [XenditController::class, 'getVirtualAccount'])->name('xendit.index');
Route::post('xendit/va/callback', [XenditController::class, 'callbackVa']);

//ROUTE untuk ADMIN
// CheckRole 1 untuk Admin
Route::group(['middleware' => ['auth','checkRole:1']], function () {
    Route::prefix('admin')->group(function () {
        Route::resource('role', RoleController::class)->except(['create', 'edit']);
        Route::resource('menu', MenuController::class)->except(['create', 'edit']);
        Route::resource('kategori', KategoriController::class)->except(['create', 'edit']);
        Route::resource('promo', PromoController::class)->except(['create', 'edit']);
        Route::resource('user', UserController::class);
        Route::resource('order-admin', OrderAdminController::class)->only(['index', 'update']);
        Route::get('order-admin/{no_resi}','App\Http\Controllers\Admin\OrderAdminController@getDetail')->name('detail-order');
        Route::resource('about', AboutController::class)->except('destroy');
        Route::get('xendit/va/transaksi', [XenditController::class, 'getTransaksi']);
        Route::get('xendit/invoice', [XenditController::class, 'getInvoice'])->name('xendit.invoice');
        Route::get('xendit/invoice/{external_id}', [XenditController::class, 'detailInvoice'])->name('xendit.detail-invoice');
        Route::prefix('gallery')->group(function () {
            Route::get('/', [GalleryController::class, 'index'])->name('gallery.index');
            Route::post('/store', [GalleryController::class, 'store'])->name('gallery.store');
            Route::get('/delete/{id}', [GalleryController::class, 'destroy'])->name('gallery.delete');
        });
    });
});

// ROUTE untuk KITCHEN
// CheckRole 2 untuk Kitchen
Route::group(['middleware' => ['auth', 'checkRole:2']], function () {
    Route::prefix('kitchen')->group(function () {
        Route::resource('dashboard-kitchen', DashboardKitchenController::class);
        Route::resource('order-kitchen', OrderKitchenController::class);
        Route::get('order/{no_resi}','App\Http\Controllers\Kitchen\OrderKitchenController@getDetail')->name('kitchen-order');
        Route::resource('kurir', KurirController::class);
        Route::match(['put', 'patch'],'status_kurir/{no_resi}', 'App\Http\Controllers\Kurir\KurirController@status_kurir')->name('status_kurir');
    });
});

// ROUTE untuk MEMBER
// CheckRole 3 untuk Member
Auth::routes(['verify' => true]);
Route::group(['middleware' => ['auth', 'verified','checkRole:3']], function (){
    Route::prefix('user')->group(function () {
        Route::resource('dashboard-user', DashboardUserController::class);
        Route::resource('setting-profile', SettingProfileController::class);
        Route::get('cart-list', [CartController::class, 'index'])->name('cart.index');
        Route::post('cart-list', [CartController::class, 'addToCart'])->name('cart.store');
        Route::post('update-cart', [CartController::class, 'updateCart'])->name('cart.update');
        Route::post('remove-cart', [CartController::class, 'removeCart'])->name('cart.remove');
        Route::post('clear-cart', [CartController::class, 'clearAllCart'])->name('cart.clear');
        Route::get('order/{no_resi}','App\Http\Controllers\User\OrderController@getDetail')->name('order-detail');
        Route::get('riwayat/{no_resi}','App\Http\Controllers\User\DashboardUserController@getRiwayat')->name('riwayat-order');
        Route::resource('order', OrderController::class);
        Route::resource('shipping-address', ShippingAddressController::class);
        Route::get('/getKota/{id}', [ShippingAddressController::class, 'getKota'])->name('getKota');
        Route::get('/getKecamatan/{id}', [ShippingAddressController::class, 'getKecamatan'])->name('getKecamatan');
        Route::get('/getKelurahan/{id}', [ShippingAddressController::class, 'getKelurahan'])->name('getKelurahan');
    });
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;

    protected $table = 'order';

    protected $fillable = [
        'no_resi'
    ];

    // public function user()
    // {
    //     return $this->belongsTo('App\Models\User', 'user_id', 'id');
    // }

    public function transaksi()
    {
        return $this->belongsTo(Transaksi::class, 'no_resi', 'no_resi');
    }

    public function xendit_invoice()
    {
        return $this->belongsTo(XenditInvoice::class, 'no_resi', 'no_resi');
    }
}

app/Http/Controllers/API/OrderController.php
<?php

namespace App\Http\Controllers\API;

use Validator;
use Carbon\Carbon;
use App\Models\User;
use App\Models\Order;
use App\Models\Riwayat;
use App\Models\Transaksi;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Http\Resources\OrderResource as OrderResource;
use App\Http\Controllers\API\BaseController as BaseController;

class OrderController extends BaseController
{
    public function index()
    {
        $order = Transaksi::where('user_id', Auth::id())->with(['order', 'user'])->get();
        return $this->handleResponse(OrderResource::collection($order), 'Data Orderan Berhasil Ditarik');
    }

    public function store(Request $request)
    {
        $input_transaksi = $request->all();
        $validator_transaksi = Validator::make($input_transaksi, [
            'no_resi' => 'required',
            'user_id' => 'required',
            'total' => 'required'
        ]);

        $input_order = $request->all();
        $validator_order = Validator::make($input_transaksi, [
            'no_resi' => 'required',
            'status_order' => 'required'
        ]);

        if($validator_transaksi->fails()){
            return $this->handleError($validator_transaksi->errors());
        }

        if($validator_order->fails()){
            return $this->handleError($validator_order->errors());
        }
        dd($request->all());
        Mail::to($request->email)->send(new OrderMail());

        if(Mail::failures()){
            return response()->Fail('Sorry! Please try again latter');
        } else {
            // return response()->success('Great! Successfully send in your mail');
            \Cart::clear();
            return $this->handleResponse(new MenuResource($menu), 'Success');
        }
    }

    public function upload_bukti(Request $request, $id)
    {
        $tgl = Carbon::now()->format('Y-m-d');
        $jam = Carbon::now()->format('H:i:s');
        $desc = "Nomor Resi ". $request->no_resi ." Telah upload bukti transfer";
        $icon = "fa fa-upload";
        // dd($request->all());
        $riwayat = new Riwayat();
        $riwayat->no_resi = $request->no_resi;
        $riwayat->tanggal = $tgl;
        $riwayat->jam = $jam;
        $riwayat->deskripsi = $desc;
        $riwayat->icon = $icon;
        $riwayat->save();


        $file = $request->file('bukti_transfer');
        $name = time();
        $extension = $file->getClientOriginalExtension();
        $newName = $name . '.' . $extension;
        $path =  $file->move('assets/admin/bukti_transfer',$newName);

        $statusTF = "Pembayaran sedang direview";
        $upload = Order::firstWhere('id', $id);

        // dd($upload);
        $upload->status_order = $statusTF;
        $upload->bukti_transfer = $newName;
        $upload->save();

        return response(['order' => $upload], 201);
    }
}

app/Http/Controllers/User/OrderController.php
<?php

namespace App\Http\Controllers\User;

use Mail;
use Xendit\Xendit;
use Carbon\Carbon;
use App\Models\Order;
Use App\Mail\OrderMail;
use App\Models\Riwayat;
use App\Models\Transaksi;
use App\Models\XenditInvoice;
use App\Models\ShippingAddress;
use Illuminate\Http\Request;
use App\Models\DetailTransaksi;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
    public function index()
    {
        $detail_order = Transaksi::where('user_id', Auth::id())->with(['order', 'user'])->get();

        return view('user-page.order.index', compact('detail_order'));
    }

    public function getDetail(Request $request,$no_resi){
        $data = Transaksi::where('no_resi',$no_resi)->with([
            'detail_transaksi'=> function($query){
                return $query->with([
                    'menu'=> function($q){
                        return $q->with('kategori');
                    }
                ]);
            }
            ,'user', 'shipping'])->first();

        return response()->json($data, 200);
    }

    public function store(Request $request)
    {
        Xendit::setApiKey(env('API_KEY'));
        $tanggal = now()->format('dmy');
        $pass = substr(str_shuffle("0123456789"), 0, 5);
        $uniqueID = $tanggal.$pass;
        $invoice = [
            "external_id" => "SS-" .$uniqueID,
            "description" => "Pembayaran dengan No. Resi ". $request->no_resi,
            "amount" => $request->grand_total,
            "customer" => [
                'name' => $request->nama,
                'email' => $request->email,
                'mobile_number' => $request->nohp,
            ],
            "customer_notification_preference" => [
                'invoice_created' => [
                    'whatsapp',
                    'sms',
                    'email',
                    'viber'
                ],
                'invoice_reminder' => [
                    'whatsapp',
                    'sms',
                    'email',
                    'viber'
                ],
                'invoice_paid' => [
                    'whatsapp',
                    'sms',
                    'email',
                    'viber'
                ],
                'invoice_expired' => [
                    'whatsapp',
                    'sms',
                    'email',
                    'viber'
                ]
            ]
        ];
        $createInvoice = \Xendit\Invoice::create($invoice);
        $id = $createInvoice['id'];
        $getInvoice = \Xendit\Invoice::retrieve($id);
        // print_r($getInvoice); die();
        // dd($createInvoice);
        // die($createInvoice['customer']['mobile_number']);

        $status_awal = "Menunggu Pembayaran";

        //INSERT DETAIL TRANSAKSI
        foreach($request->menu_id as $key => $menu_id){
            $detail = new DetailTransaksi();

            $detail->no_resi = $request->no_resi;
            $detail->menu_id = $menu_id;
            $detail->qty = $request->qty[$key];
            $detail->subtotal = $request->subtotal[$key];
            $detail->save();
        }
        //INSERT XENDIT INVOICE
        $invoice = new XenditInvoice;
        $invoice->id = $createInvoice['id'];
        $invoice->external_id = $createInvoice['external_id'];
        $invoice->user_id = $createInvoice['user_id'];
        $invoice->no_resi = $request->no_resi;
        $invoice->status = $createInvoice['status'];
        $invoice->merchant_name = $createInvoice['merchant_name'];
        $invoice->amount = $createInvoice['amount'];
        $invoice->description = $createInvoice['description'];
        $invoice->expiry_date = $createInvoice['expiry_date'];
        $invoice->invoice_url = $createInvoice['invoice_url'];
        $invoice->customer_email = $createInvoice['customer']['email'];
        $invoice->customer_mobile_number = $createInvoice['customer']['mobile_number'];
        $invoice->save();
        //INSERT TRANSAKSI
        $transaksi = new Transaksi();
        $transaksi->no_resi = $request->no_resi;
        $transaksi->user_id = $request->user_id;
        $transaksi->shipping_id = $request->shipping_id;
        $transaksi->jarak = $request->jarak;
        $transaksi->ongkir = $request->ongkir;
        $transaksi->total = $request->total;
        $transaksi->grand_total = $request->grand_total;
        $transaksi->save();

        //INSERT ORDER
        $order = new Order();
        $order->no_resi = $request->no_resi;
        $order->status_order = $status_awal;
        $order->save();

        $tgl = Carbon::now()->format('Y-m-d');
        $jam = Carbon::now()->format('H:i:s');
        $desc = "Order menu dengan Nomor Resi ". $request->no_resi;
        $icon = "fa fa-shopping-cart";
        //INSERT RIWAYAT ORDER
        $riwayat = new Riwayat();
        $riwayat->no_resi = $request->no_resi;
        $riwayat->tanggal = $tgl;
        $riwayat->jam = $jam;
        $riwayat->deskripsi = $desc;
        $riwayat->icon = $icon;
        $riwayat->save();


        Mail::to($request->email)->send(new OrderMail());

        if(Mail::failures()){
            return response()->with([
                alert()->warning('Gagal', 'Pesanan Gagal')
            ]);
        } else {
            \Cart::clear();
            session()->flash('newurl', $createInvoice['invoice_url']);
            return redirect()->back()->with([
                alert()->success('Sukses', 'Link Pembayaran telah dikirim ke Email dan Whatsapp Anda')
            ]);
            // return redirect($createInvoice['invoice_url']);
        }
    }

    public function update(Request $request, $id)
    {
        $tgl = Carbon::now()->format('Y-m-d');
        $jam = Carbon::now()->format('H:i:s');
        $desc = "Nomor Resi ". $request->no_resi ." Telah upload bukti transfer";
        $icon = "fa fa-upload";

        $riwayat = new Riwayat();
        $riwayat->no_resi = $request->no_resi;
        $riwayat->tanggal = $tgl;
        $riwayat->jam = $jam;
        $riwayat->deskripsi = $desc;
        $riwayat->icon = $icon;
        $riwayat->save();

        $cari = Order::firstWhere('id', $id);

        $file = $request->file('bukti_transfer');
        $name = time();
        $extension = $file->getClientOriginalExtension();
        $newName = $name . '.' . $extension;
        $path =  $file->move('assets/admin/bukti_transfer',$newName);
        $statusTF = "Pembayaran sedang direview";
        $cari->bukti_transfer = $newName;
        $cari->status_order = $statusTF;

        $cari->save();
        return redirect()->route('order.index');
    }
}

resources/views/kitchen-page/order/index.blade.php
@extends('kitchen-layout.main')

@section('content')
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Order</h1>
        </div>
        <div class="section-body">
            <h2 class="section-title">Ready to Cook</h2>
            <div class="row">
                @foreach ($antrian as $i)
                    @if ($i->finish == NULL)
                    <div class="col-12 col-md-6 col-lg-4">
                        <div class="card card-danger">
                            <div class="card-header" >
                                <h4 style="color: red">{{ $i->transaksi->user->name }} - {{ $i->no_resi }}</h4>
                                <div class="card-header-action">
                                    <div class="btn btn-danger no_resi" data-id="{{ $i->no_resi }}" >
                                        Antrian : {{ $i->no_antrian }}
                                    </div>
                                </div>
                            </div>
                            <div id="data-order">
                                <div class="card-body">
                                    @foreach ($i->transaksi->detail_transaksi as $j)
                                    <div style="font-weight: bolder">
                                        {{ $j->menu->kategori->kategori }}
                                    </div>
                                    <ul>
                                        <li>[{{ $j->qty }}] x {{ $j->menu->nama_menu }}</li>
                                    </ul>
                                    @endforeach
                                    <div class="text-right">
                                        <u>{{ $i->created_at->isoformat('dddd, d-MMMM-Y') }}</u><br>
                                        <i class="fas fa-clock"></i> <i>{{ $i->start->diffForHumans() }}</i>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer text-right">
                                <button class="btn btn-danger" data-toggle="modal" data-target="#cariKurir{{ $i->no_resi }}" style="width: 100%">Order Ready, Pesan Kurir</button>
                            </div>
                        </div>
                    </div>
                    @else
                    {{-- <div class="col-12 col-md-6 col-lg-4">
                        <div class="card card-primary">
                            <div class="card-header">
                                <h4>Selesai</h4>
                            </div>
                            <div class="card-body">
                                <p>{{ $i->transaksi->user->name }} - {{ $i->no_resi }}</p>
                                <p>Selesai : <i class="fas fa-clock"></i> <i>{{ $i->finish->diffForHumans() }}</i></p>
                            </div>
                        </div>
                    </div> --}}
                    @endif
                @endforeach
            </div>



            <h2 class="section-title">On The Way</h2>
            <div class="row">
                @foreach ($kurir as $i)
                @if ($i->status == "Sedang dalam Perjalanan")
                {{-- Loop Card Sedang Diantar start --}}
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="card card-info">
                        <div class="card-header">
                            <h4 style="color: #3ABAF4">{{ $i->transaksi->user->name }} - {{ $i->no_resi }}</h4>
                            <div class="card-header-action">
                                <div class="btn btn-info">
                                    No. Antrian : {{ $i->antrian_order->no_antrian }}
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            {{-- Looping Kategori start --}}
                                @foreach ($i->transaksi->detail_transaksi as $j)
                                <div style="font-weight: bolder">
                                    {{ $j->menu->kategori->kategori }}
                                    <ul>
                                        <li>[{{ $j->qty }}] x {{ $j->menu->nama_menu }}</li>
                                    </ul>
                                </div>
                                @endforeach
                            <span style="color: green; font-weight: bolder">GOJEK</span> '{{ $i->name }}' - {{ $i->no_plat }} <a href="{{ $i->link_track }}" target="blank_" class="btn btn-secondary ml-2 my-3">Track Kurir</a>
                            <div class="text-right">
                                <u>{{ $i->updated_at->isoformat('dddd, d-MMMM-Y') }}</u><br>
                                <i class="fas fa-clock"></i> <i>{{ $i->updated_at->diffForHumans() }}</i>
                            </div>
                            {{-- Looping Kategori end --}}
                        </div>
                        <div class="card-footer text-right">
                            <button class="btn btn-info" data-toggle="modal" data-target="#selesaiKurir{{ $i->no_resi }}" style="width: 100%">Kurir Sudah Sampai</button>
                        </div>
                    </div>
                </div>
                @endif
                {{-- Loop Card Sedang Diantar end --}}
                @endforeach
            </div>

            <h2 class="section-title">Delivered</h2>
            <div class="row">
                @foreach ($kurir as $i)
                @if ($i->status == "Kurir sudah sampai")
                {{-- Loop Card Sedang Diantar start --}}
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="card card-success">
                        <div class="card-header">
                            <h4>{{ $i->transaksi->user->name }} - {{ $i->no_resi }}</h4>
                            <div class="card-header-action">
                                <div class="btn btn-success">
                                    No. Antrian : {{ $i->antrian_order->no_antrian }}
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            {{-- Looping Kategori start --}}
                                @foreach ($i->transaksi->detail_transaksi as $j)
                                <div style="font-weight: bolder">
                                    {{ $j->menu->kategori->kategori }}
                                    <ul>
                                        <li>[{{ $j->qty }}] x {{ $j->menu->nama_menu }}</li>
                                    </ul>
                                </div>
                                @endforeach
                            <span style="color: green; font-weight: bolder">GOJEK</span> '{{ $i->name }}' - {{ $i->no_plat }} <a href="{{ $i->link_track }}" class="btn btn-secondary ml-2 my-3">Track Kurir</a>
                            <div class="text-right">
                                <u>{{ $i->updated_at->isoformat('dddd, d-MMMM-Y') }}</u><br>
                                <i class="fas fa-clock"></i> <i>{{ $i->updated_at->diffForHumans() }}</i>
                            </div>
                            {{-- Looping Kategori end --}}
                        </div>
                    </div>
                </div>
                @endif
                {{-- Loop Card Sedang Diantar end --}}
                @endforeach
            </div>
        </div>
    </section>
</div>

@include('kitchen-page.order.modal')
@endsection

@section('js')
{{-- <script type="text/javascript">
    $(document).ready(function(){
        var idx = $('.no_resi').attr('data-id')
        // console.log(idx);
        var data_order = $('#data-order')
        data_order.html('')

        $.ajax({
            url:"{{ url('kitchen/order') }}/"+idx,
            method:'get',
            success:function(res){
                // console.log(res)
                $.each(res.detail_transaksi, function(idk, val){
                    data_order.append(`
                        <div class="card-body">
                            <div style="font-weight: bolder">
                                ${val.menu.kategori.kategori}
                            </div>
                            <ul>
                                <li>[${val.qty}] x [${val.menu.nama_menu}]</li>
                            </ul>
                        </div>
                    `)
                })
            },
            error: function(xhr, status, error) {
                // alert(xhr.responseText);
                alert("error")
            }
        })
    })
</script> --}}
@endsection

resources/views/kitchen-page/order/modal.blade.php
@foreach ($antrian as $i)
<!-- Modal Info Kurir -->
<form action="{{ url('kitchen/kurir', $i->no_resi) }}" method="post" enctype="multipart/form-data">
    {{-- <form action="{{ route('kurir.store') }}" method="post" enctype="multipart/form-data"> --}}
    @csrf
    @method('PATCH')
    <div class="modal fade" id="cariKurir{{ $i->no_resi }}" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    Informasi Kurir
                </div>
                <div class="modal-body">
                    <input type="text" class="form-control" name="no_resi" value="{{ $i->transaksi->no_resi }}">
                    <div class="form-group">
                        <label>Nama Kurir</label>
                        <input type="text" name="name" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Plat Nomor</label>
                        <input type="text" name="no_plat" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Link Track Kurir</label>
                        <input type="url" name="link_track" class="form-control">
                    </div>
                </div>
                <div class="modal-footer text-right">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success">Save</button>
                </div>
            </div>
        </div>
    </div>
</form>
@endforeach


@foreach ($kurir as $i)
<form action="{{ url('kitchen/status_kurir', $i->no_resi) }}" method="post" enctype="multipart/form-data">
    @csrf
    @method('PATCH')
    <div class="modal fade" id="selesaiKurir{{ $i->no_resi }}" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    Informasi Kurir
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Nama Kurir</label>
                        <input type="text" class="form-control" name="name" value="{{ $i->name }}">
                    </div>
                    <div class="form-group">
                        <label>Plat Nomor</label>
                        <input type="text" class="form-control" name="no_plat" value="{{ $i->no_plat }}">
                    </div>
                    <div class="form-group">
                        <label>Link Track Kurir</label>
                        <input type="text" class="form-control" name="link_track" value="{{ $i->link_track }}">
                    </div>
                    <div class="form-group">
                        <label>No. Resi</label>
                        <input type="text" class="form-control" name="no_resi" value="{{ $i->no_resi }}" readonly>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="status_kurir" value="Kurir sudah sampai" readonly>
                    </div>
                </div>
                <div class="card-footer text-right">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">Close</span>
                    </button>
                    <button type="submit" class="btn btn-primary">
                        <span aria-hidden="true">Kurir Sudah Sampai</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>
@endforeach